import { Command } from 'commander';
import { existsSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { validateInstanceId } from '../utils/validate.js';

export const PM2_SUPERVISOR_POLICY = {
  killTimeoutMs: 60_000,
  listenTimeoutMs: 120_000,
  minUptimeMs: 10_000,
  maxRestarts: 10,
  expBackoffRestartDelayMs: 5_000,
  shutdownWithMessage: true,
  waitReady: true,
  filterEnv: ['GITHUB_', 'GH_', 'TOKEN', 'SECRET', 'API_KEY', 'ACCESS_KEY', 'PRIVATE_KEY', 'PASSWORD', 'CREDENTIAL'],
} as const;

export function daemonAppName(instanceId: string): string {
  return `cortextos-daemon-${instanceId}`;
}

export function dashboardAppName(instanceId: string): string {
  return `cortextos-dashboard-${instanceId}`;
}

export function dashboardPortForInstance(instanceId: string): number {
  if (instanceId === 'default') return 3000;
  let hash = 2166136261;
  for (const char of instanceId) {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return 3100 + ((hash >>> 0) % 20_000);
}

export function resolveFrameworkRoot(): string {
  if (process.env.CTX_FRAMEWORK_ROOT) return process.env.CTX_FRAMEWORK_ROOT;
  if (process.env.CTX_PROJECT_ROOT) return process.env.CTX_PROJECT_ROOT;
  const canonical = join(homedir(), 'cortextos');
  return existsSync(join(canonical, 'dist', 'daemon.js')) ? canonical : process.cwd();
}

export const ecosystemCommand = new Command('ecosystem')
  .option('--instance <id>', 'Instance ID', 'default')
  .option('--org <name>', 'Organization name (auto-detected if not specified)')
  .option('--output <path>', 'Output file', 'ecosystem.config.js')
  .description('Generate ecosystem.config.js from agent configs')
  .action(async (options: { instance: string; org?: string; output: string }) => {
    validateInstanceId(options.instance);
    const projectRoot = resolveFrameworkRoot();

    const agents: Array<{ name: string; dir: string; org?: string }> = [];
    const orgsDir = join(projectRoot, 'orgs');
    if (existsSync(orgsDir)) {
      for (const org of readdirSync(orgsDir, { withFileTypes: true })) {
        if (!org.isDirectory()) continue;
        const agentsDir = join(orgsDir, org.name, 'agents');
        if (!existsSync(agentsDir)) continue;
        for (const agent of readdirSync(agentsDir, { withFileTypes: true })) {
          if (!agent.isDirectory()) continue;
          agents.push({ name: agent.name, dir: join(agentsDir, agent.name), org: org.name });
        }
      }
    }

    if (agents.length === 0) {
      console.log('No agents found. Add agents first: cortextos add-agent <name>');
      return;
    }

    const detectedOrg = options.org || agents.find(a => a.org)?.org || '';
    if (!detectedOrg) {
      console.error('Could not determine org. Use --org <name>.');
      return;
    }

    const dashboardDir = join(projectRoot, 'dashboard');
    // BUG-019 + cycle-2 finding: require BOTH package.json AND node_modules/.bin/next.
    // Without the second check, running `cortextos ecosystem` before `npm install`
    // in dashboard/ produces a crash-looped PM2 entry. Skip the dashboard entry
    // until deps are installed; re-run `cortextos ecosystem` afterwards to add it.
    const hasDashboard = existsSync(join(dashboardDir, 'package.json')) &&
      existsSync(join(dashboardDir, 'node_modules', '.bin', 'next'));
    const dashboardScriptExpression = process.platform === 'win32'
      ? "path.join(FRAMEWORK_ROOT, 'dashboard', 'node_modules', 'next', 'dist', 'bin', 'next')"
      : "'npm'";
    const dashboardArgs = process.platform === 'win32' ? 'dev' : 'run dev';

    const dashboardAppBlock = hasDashboard
      ? `,
    {
      name: 'cortextos-dashboard-' + INSTANCE_ID,
      script: ${dashboardScriptExpression},
      args: ${JSON.stringify(dashboardArgs)},
      cwd: path.join(FRAMEWORK_ROOT, 'dashboard'),
      env: {
        PORT: DASHBOARD_PORT,
        CTX_DASHBOARD_PORT: DASHBOARD_PORT,
        CTX_INSTANCE_ID: INSTANCE_ID,
        CTX_ROOT: CTX_ROOT,
        CTX_FRAMEWORK_ROOT: FRAMEWORK_ROOT,
        CTX_PROJECT_ROOT: FRAMEWORK_ROOT,
        CTX_ORG: CTX_ORG,
        PATH: process.env.PATH,
        PATHEXT: process.env.PATHEXT,
      },
      windowsHide: true,
      kill_timeout: ${PM2_SUPERVISOR_POLICY.killTimeoutMs},
      listen_timeout: ${PM2_SUPERVISOR_POLICY.listenTimeoutMs},
      min_uptime: ${PM2_SUPERVISOR_POLICY.minUptimeMs},
      max_restarts: ${PM2_SUPERVISOR_POLICY.maxRestarts},
      exp_backoff_restart_delay: ${PM2_SUPERVISOR_POLICY.expBackoffRestartDelayMs},
      filter_env: ${JSON.stringify(PM2_SUPERVISOR_POLICY.filterEnv)},
      autorestart: true,
    }`
      : '';

    const content = `// AUTO-GENERATED by \`cortextos ecosystem\`. Do NOT edit by hand.
// Re-run \`cortextos ecosystem\` to regenerate.
const path = require('path');
const os = require('os');

const FRAMEWORK_ROOT = process.env.CTX_FRAMEWORK_ROOT || ${JSON.stringify(projectRoot)};
const INSTANCE_ID = process.env.CTX_INSTANCE_ID || ${JSON.stringify(options.instance)};
const CTX_ROOT = process.env.CTX_ROOT || path.join(os.homedir(), '.cortextos', INSTANCE_ID);
const CTX_ORG = process.env.CTX_ORG || ${JSON.stringify(detectedOrg)};
function dashboardPortForInstance(instanceId) {
  if (instanceId === 'default') return 3000;
  let hash = 2166136261;
  for (const char of instanceId) {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return 3100 + ((hash >>> 0) % 20000);
}
const DASHBOARD_PORT = process.env.CTX_DASHBOARD_PORT || String(dashboardPortForInstance(INSTANCE_ID));

module.exports = {
  apps: [
    {
      name: 'cortextos-daemon-' + INSTANCE_ID,
      script: path.join(FRAMEWORK_ROOT, 'dist', 'daemon.js'),
      args: '--instance ' + INSTANCE_ID,
      cwd: FRAMEWORK_ROOT,
      env: {
        CTX_INSTANCE_ID: INSTANCE_ID,
        CTX_ROOT: CTX_ROOT,
        CTX_FRAMEWORK_ROOT: FRAMEWORK_ROOT,
        CTX_PROJECT_ROOT: FRAMEWORK_ROOT,
        CTX_ORG: CTX_ORG,
        PATH: process.env.PATH,
        PATHEXT: process.env.PATHEXT,
      },
      kill_timeout: ${PM2_SUPERVISOR_POLICY.killTimeoutMs},
      listen_timeout: ${PM2_SUPERVISOR_POLICY.listenTimeoutMs},
      min_uptime: ${PM2_SUPERVISOR_POLICY.minUptimeMs},
      max_restarts: ${PM2_SUPERVISOR_POLICY.maxRestarts},
      exp_backoff_restart_delay: ${PM2_SUPERVISOR_POLICY.expBackoffRestartDelayMs},
      shutdown_with_message: ${PM2_SUPERVISOR_POLICY.shutdownWithMessage},
      wait_ready: ${PM2_SUPERVISOR_POLICY.waitReady},
      filter_env: ${JSON.stringify(PM2_SUPERVISOR_POLICY.filterEnv)},
      autorestart: true,
    }${dashboardAppBlock},
  ],
};
`;

    writeFileSync(options.output, content, 'utf-8');
    console.log(`Generated ${options.output} with daemon (manages ${agents.length} agents)${hasDashboard ? ' + dashboard' : ''}`);
    console.log('\nStart with:');
    console.log(`  cortextos start --instance ${options.instance}`);
  });