import { Command } from 'commander';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

export const goalsCommand = new Command('goals')
  .description('Manage goals.json and auto-generate GOALS.md for agents');

// cortextos goals generate-md --agent <name> --org <org>
goalsCommand
  .command('generate-md')
  .description('Regenerate GOALS.md from goals.json for an agent')
  .requiredOption('--agent <name>', 'Agent name')
  .requiredOption('--org <org>', 'Org name')
  .option('--force', 'Overwrite even when the source is empty and GOALS.md looks hand-maintained')
  .action((options: { agent: string; org: string; force?: boolean }) => {
    const frameworkRoot = process.env.CTX_FRAMEWORK_ROOT || process.cwd();

    if (!/^[A-Za-z0-9_-]+$/.test(options.agent) || !/^[A-Za-z0-9_-]+$/.test(options.org)) {
      process.stderr.write('Error: agent and org must be alphanumeric/dash/underscore only\n');
      process.exit(1);
    }

    const agentDir = join(frameworkRoot, 'orgs', options.org, 'agents', options.agent);
    const goalsJsonPath = join(agentDir, 'goals.json');
    const goalsMdPath = join(agentDir, 'GOALS.md');

    if (!existsSync(goalsJsonPath)) {
      process.stderr.write(`goals.json not found at ${goalsJsonPath}\n`);
      process.exit(1);
    }

    let data: Record<string, unknown>;
    try {
      data = JSON.parse(readFileSync(goalsJsonPath, 'utf-8'));
    } catch {
      process.stderr.write(`Failed to parse goals.json for ${options.agent}\n`);
      process.exit(1);
    }

    const goals = Array.isArray(data.goals) ? (data.goals as Array<string | { title: string }>) : [];
    const focus = typeof data.focus === 'string' ? data.focus : '';
    const bottleneck = typeof data.bottleneck === 'string' ? data.bottleneck : '';
    const updatedAt = typeof data.updated_at === 'string' ? data.updated_at : new Date().toISOString();
    const updatedBy = typeof data.updated_by === 'string' ? data.updated_by : '';

    const lines: string[] = [
      '# Goals',
      '',
      '> Auto-generated from goals.json. Do not edit this file directly.',
      `> To regenerate: \`cortextos goals generate-md --agent ${options.agent} --org ${options.org}\``,
      '',
      '## Focus',
      focus || '(not set — check with your orchestrator)',
      '',
      '## Goals',
    ];

    if (goals.length === 0) {
      lines.push('(none set — message your orchestrator to request today\'s goals)');
    } else {
      goals.forEach((g, i) => {
        const title = typeof g === 'string' ? g : (g as { title: string }).title;
        lines.push(`${i + 1}. ${title}`);
      });
    }

    lines.push(
      '',
      '## Bottleneck',
      bottleneck || '(none)',
      '',
      '## Updated',
      updatedBy ? `${updatedAt} (by ${updatedBy})` : updatedAt,
      '',
    );

    // Refuse to destroy hand-maintained content with an empty source.
    //
    // generate-md previously wrote unconditionally, so running it against an
    // agent whose goals.json is empty replaced a real GOALS.md with a stub. On
    // 2026-07-27 SIX of sixteen agents were in exactly that state (atlas,
    // brand_writer, email_triage, pm_bot, todoist_keeper, vault_keeper), with up
    // to 5.4KB of hand-written content each, including a client-facing quality
    // gate added minutes earlier. One routine regen would have silently erased
    // it, and nothing would have reported an error.
    //
    // Deliberately narrow: this only blocks when the SOURCE has nothing to say
    // AND the existing file was never generated by this command. A previously
    // generated file carries the marker below and stays freely regenerable, so
    // the normal path is untouched.
    const GENERATED_MARKER = 'Auto-generated from goals.json';
    const sourceIsEmpty = goals.length === 0 && !focus && !bottleneck;
    if (sourceIsEmpty && !options.force && existsSync(goalsMdPath)) {
      const current = readFileSync(goalsMdPath, 'utf-8');
      const handMaintained = !current.includes(GENERATED_MARKER) && current.trim().length > 200;
      if (handMaintained) {
        process.stderr.write(
          `Refusing to overwrite ${goalsMdPath}\n` +
            `  goals.json has no goals, focus or bottleneck, but GOALS.md holds ${current.length} bytes ` +
            `of content this command did not generate.\n` +
            `  Regenerating would replace it with an empty stub.\n` +
            `  Populate goals.json first, or pass --force if the loss is intended.\n`
        );
        process.exit(1);
      }
    }
    writeFileSync(goalsMdPath, lines.join('\n'), 'utf-8');
    console.log(`Generated GOALS.md for ${options.agent}`);
  });
